# Generated by Django 3.2 on 2023-05-17 14:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('createupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.createupdate')),
                ('type', models.CharField(choices=[('MAIL', 'Почтовая рассылка')], help_text='Выберите тип уведомления', max_length=40, verbose_name='Тип уведомления')),
                ('text', models.TextField(help_text='Уведомления', max_length=400, verbose_name='Уведомление')),
                ('author', models.ForeignKey(help_text='Администратор создавший уведомление', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Администратор создавший уведомление')),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': 'Уведомления пользователей',
                'ordering': ['created_at'],
            },
            bases=('admin_panel.createupdate',),
        ),
        migrations.CreateModel(
            name='NotificationFrequency',
            fields=[
                ('createupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.createupdate')),
                ('type', models.SlugField(help_text='Выберите тип уведомления', max_length=40, verbose_name='Тип уведомления')),
                ('frequency', models.PositiveIntegerField(help_text='Выберите тип уведомления', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Периодичность отправки уведомления в минутах')),
            ],
            options={
                'verbose_name': 'Периодичность уведомлений',
                'verbose_name_plural': 'Периодичности уведомлений',
                'ordering': ['created_at'],
            },
            bases=('admin_panel.createupdate',),
        ),
        migrations.CreateModel(
            name='UsersNotification',
            fields=[
                ('createupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.createupdate')),
                ('user_id', models.UUIDField(help_text='Укажите id пользователя', null=True, verbose_name='Пользователь')),
                ('content_id', models.UUIDField(help_text='Укажите id контента', null=True, verbose_name='Контент')),
                ('notification_id', models.ForeignKey(help_text='Укажите id уведомления', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_panel.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': 'Уведомления пользователей',
                'ordering': ['created_at'],
            },
            bases=('admin_panel.createupdate',),
        ),
    ]
