# Generated by Django 3.2 on 2023-06-14 11:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('mail', 'Почтовая рассылка'), ('regular_mail', 'Регулярная почтовая рассылка')], help_text='Выберите тип уведомления', max_length=40, verbose_name='Тип уведомления')),
                ('is_express', models.BooleanField(default=False, help_text='Выберете, если надо уведомить всех срочно', verbose_name="Поле указывающее на срочность уведомления'")),
                ('text', models.TextField(help_text='Текст уведомления', max_length=400, verbose_name='Текст уведомление')),
                ('title', models.CharField(help_text='Заголовок уведомления', max_length=100, verbose_name='Заголовок уведомление')),
                ('content_id', models.UUIDField(help_text='Укажите id контента', null=True, verbose_name='Контент')),
                ('author', models.ForeignKey(blank=True, help_text='Администратор создавший уведомление', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Администратор создавший уведомление')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsersUnsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(help_text='Укажите id пользователя', null=True, unique=True, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отказ от получения рассылок пользователя',
                'verbose_name_plural': 'Отказы от получения рассылок пользователей',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsersNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.UUIDField(help_text='Укажите id пользователя', null=True, verbose_name='Пользователь')),
                ('email', models.EmailField(blank=True, help_text='Почта на которую было направлено уведомление', max_length=254, null=True, verbose_name='Почта на которую было направлено уведомление')),
                ('is_user_subscribed', models.BooleanField(default=True, help_text='Поле указывающее согласен ли на рассылку пользователь', verbose_name='Поле указывающее согласен ли на рассылку пользователь')),
                ('is_sent_to_queue', models.BooleanField(default=True, verbose_name='Поле указывающее поставлено ли сообщение в очередь на отправку')),
                ('notification', models.ForeignKey(help_text='Укажите id уведомления', on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_notifications', to='admin_panel.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': 'Уведомления пользователей',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Уникальное название уведомления', max_length=40, verbose_name='Уникальное название уведомления')),
                ('frequency', models.PositiveIntegerField(help_text='Периодичность отправки уведомления в секундах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Периодичность отправки уведомления в секундах')),
                ('users_ids', models.TextField(help_text='Список uuid пользователей для отправки уведомлений', verbose_name='Список uuid пользователей для отправки уведомлений')),
                ('notification', models.ForeignKey(help_text='Укажите id уведомления', on_delete=django.db.models.deletion.DO_NOTHING, related_name='frequency', to='admin_panel.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Периодичность уведомлений',
                'verbose_name_plural': 'Периодичности уведомлений',
                'ordering': ['created_at'],
            },
        ),
    ]
