# Generated by Django 3.2 on 2023-06-16 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('slug', models.SlugField(help_text='set slug', unique=True, verbose_name='slug')),
                ('password', models.CharField(help_text='set password', max_length=128, verbose_name='password')),
            ],
            options={
                'verbose_name': ('Opting out of receiving user mailings',),
                'verbose_name_plural': ('Opting out of receiving user mailings',),
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationfrequency',
            options={'ordering': ['created_at'], 'verbose_name': 'notification frequency', 'verbose_name_plural': 'notifications frequencies'},
        ),
        migrations.AlterModelOptions(
            name='usersnotification',
            options={'ordering': ['created_at'], 'verbose_name': 'users notification', 'verbose_name_plural': 'users notifications'},
        ),
        migrations.AlterModelOptions(
            name='usersunsubscribe',
            options={'ordering': ['created_at'], 'verbose_name': ('Opting out of receiving user mailings',), 'verbose_name_plural': ('Opting out of receiving user mailings',)},
        ),
        migrations.AlterField(
            model_name='notification',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The administrator who created the notification', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='The administrator who created the notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_id',
            field=models.UUIDField(help_text='set content id', null=True, verbose_name='content id'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_express',
            field=models.BooleanField(default=False, help_text='Choose if you need to notify everyone urgently', verbose_name='Field indicating the urgency of the notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(help_text='Text notification', max_length=400, verbose_name='Text notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Notice title', max_length=100, verbose_name='Notice title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('письмо на почту', 'Mail'), ('регулярная рассылка', 'Regular Mail')], help_text='Select notification type', max_length=40, verbose_name='notification_type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='notificationfrequency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='notificationfrequency',
            name='frequency',
            field=models.PositiveIntegerField(help_text='Notification frequency in seconds', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Notification frequency in seconds'),
        ),
        migrations.AlterField(
            model_name='notificationfrequency',
            name='notification',
            field=models.ForeignKey(help_text='set notification', on_delete=django.db.models.deletion.DO_NOTHING, related_name='frequency', to='admin_panel.notification', verbose_name='notification'),
        ),
        migrations.AlterField(
            model_name='notificationfrequency',
            name='slug',
            field=models.SlugField(help_text='Unique notification title', max_length=40, verbose_name='Unique notification title'),
        ),
        migrations.AlterField(
            model_name='notificationfrequency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='notificationfrequency',
            name='users_ids',
            field=models.TextField(help_text='List of uuid users to send notifications', verbose_name='List of uuid users to send notifications'),
        ),
        migrations.AlterField(
            model_name='usersnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='usersnotification',
            name='email',
            field=models.EmailField(blank=True, help_text='Mail for sending notifications', max_length=254, null=True, verbose_name='Mail for sending notifications'),
        ),
        migrations.AlterField(
            model_name='usersnotification',
            name='is_sent_to_queue',
            field=models.BooleanField(default=True, verbose_name='A field indicating whether the notifications is queued for sending'),
        ),
        migrations.AlterField(
            model_name='usersnotification',
            name='is_user_subscribed',
            field=models.BooleanField(default=True, help_text='A field indicating whether the user is subscribed to the mailing list', verbose_name='A field indicating whether the user is subscribed to the mailing list'),
        ),
        migrations.AlterField(
            model_name='usersnotification',
            name='notification',
            field=models.ForeignKey(help_text='set notification', on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_notifications', to='admin_panel.notification', verbose_name='notification'),
        ),
        migrations.AlterField(
            model_name='usersnotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='usersnotification',
            name='user_id',
            field=models.UUIDField(help_text='set user id', null=True, verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='usersunsubscribe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='usersunsubscribe',
            name='user_id',
            field=models.UUIDField(help_text='set user', null=True, unique=True, verbose_name='user'),
        ),
    ]
