# Generated by Django 3.2 on 2023-06-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20230616_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('mail', 'mail'), ('regular_mail', 'regular_mail')], help_text='Select notification type', max_length=40, verbose_name='notification_type'),
        ),
    ]
