name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    strategy:
      matrix:
        python-version: ['3.8', '3.9' ]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      id: python-version
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install dependencies
      id: dependencies
      if: always()
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide flake8-html lxml mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      id: flake8
      if: always()
      run: |
        flake8 . --format=html --htmldir output

    - name: mypy
      id: mypy
      if: always()
      run: |
         mypy .

    - name: send error message
      uses: appleboy/telegram-action@master
      if: failure()
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "
          _____________________________________________________________
          
          Project: ${{ github.repository }}
          
          Author: ${{ github.actor }}
          
          Commit: ${{ github.sha }}
          
          Python ${{ matrix.python-version }}
          
          Pipeline finished with error.
          
          Steps details - ${{ toJson(steps) }}
        "
    - name: send success message
      uses: appleboy/telegram-action@master
      if: success()
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "
          _____________________________________________________________

          Project: ${{ github.repository }}

          Author: ${{ github.actor }}

          Commit: ${{ github.sha }}

          Python ${{ matrix.python-version }}
          
          Pipeline finished successfully.
        "
